<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Dolphin Hotel</title>

</head>
<style type="text/css">
.ReadMsgBody {
	width: 100%;
}

.ExternalClass {
	width: 100%;
}

</style>
<body>

<p>Formulario de contatos</p>
<br />
<p><b>Assunto: </b><?php echo $this->assunto;?></p>
<br />
<p><b>Nome: </b><?php echo $this->nome;?></p>
<p><b>Email: </b><?php echo $this->email;?></p>
<p><b>Telefone: </b><?php echo $this->telefone;?></p>
<p><b>Mensagem: </b><?php echo $this->mensagem;?></p>
        
</body>
</html>