<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>APPCetera</title>

</head>
<style type="text/css">
.ReadMsgBody
{ width: 100%;}
.ExternalClass
{width: 100%;}
</style>
<body>
<table width="620" border="12" bordercolor="#0086B9" align="center" cellpadding="20" cellspacing="0" bgcolor="#FFFFFF">
  <tr>
    <p>Olá <?php echo $this->nome; ?>, </p>
    <p>Você solicitou a recuperação da sua senha, segue abaixo suas informações de acesso:</p>
    <p>E-mail:<b> <?php echo $this->email; ?></b></p>
    <p>Senha: <b><?php echo $this->senha; ?></b></p>
    <p>Caso não tenha solicitado por favor desconsiderar este e-mail.</p></td>
  </tr>
</table>
</body>
</html>