<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <title>Grau Técnico</title>
		<meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl('cms/css/bootstrap.min.css'); ?>" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl('cms/css/font-awesome.css'); ?>" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl('cms/css/unicorn-login.css'); ?>" />
    		<script type="text/javascript" src="js/respond.min.js"></script>
	</head>    <body>
        <div id="container">
            <div id="logo">
                <img src="img/logo.png" alt="" />
            </div>
            <div id="user">
                <div class="avatar">
                    <div class="inner"></div>
                    <img src="img/demo/av1_1.jpg" />
                </div>
                <div class="text">
                    <h4>Olá,<span class="user_name"></span></h4>
                </div>
            </div>
            <div id="loginbox">            
                <form id="loginform" action="index.html">
    				<p>Coloque o seu e-mail e a senha para continuar</p>
                    <div class="input-group input-sm">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span><input class="form-control" type="text" id="username" name="email" placeholder="Email" />
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span><input class="form-control" type="password" name="password" id="password" placeholder="Senha" />
                    </div>
                    <div class="form-actions clearfix">
                        <div class="pull-left">
                            
                        </div>
                        <div class="pull-right">
                            <a href="#recoverform" class="flip-link to-recover grey">Perdeu a senha?</a>
                        </div>
                        <input type="submit" class="btn btn-block btn-primary btn-default" value="Login" />
                    </div>

                </form>
                <form id="recoverform" action="#">
    				<p>Coloque seu e-mail para receber as instruções para recuperar sua senha</p>
    				<div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-envelope"></i></span><input class="form-control" type="text" placeholder="E-mail address" />
                    </div>
                    <div class="form-actions clearfix">
                        <div class="pull-left">
                            <a href="#loginform" class="grey flip-link to-login">Clique para ir ao login</a>
                        </div>
                        <div class="pull-right">
                        </div>
                        <input type="submit" class="btn btn-block btn-inverse" value="Recover" />
                    </div>
                </form>
                <form id="registerform" action="#">
                    <p>Enter information required to register:</p>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span><input class="form-control" type="text" placeholder="Enter Username" />
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span><input class="form-control" type="password" placeholder="Choose Password" />
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span><input class="form-control" type="password" placeholder="Confirm password" />
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-envelope"></i></span><input class="form-control" type="text" placeholder="Enter E-mail address" />
                    </div>
                    <div class="form-actions clearfix">
                        <div class="pull-left">
                            <a href="#loginform" class="grey flip-link to-login">Click to login</a>
                        </div>
                        <div class="pull-right">
                            <a href="#recoverform" class="grey flip-link to-recover">Lost password?</a>
                        </div>
                        <input type="submit" class="btn btn-block btn-success" value="Register" />
                    </div>
                </form>
            </div>
        </div>
        
        <script src="<?php echo $this->baseUrl('cms/js/jquery.min.js'); ?>"></script>  
        <script src="<?php echo $this->baseUrl('cms/js/jquery-ui.custom.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('cms/js/unicorn.login.js'); ?>"></script> 
    </body>
</html>
