<div class="row">
    <div class="col-lg-12">

        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li><a href="<?php echo $this->baseUrl('/admin'); ?>">Home</a></li>
                    <?php
                    foreach ($this->breadcrumb as $nome => $link) {
                        echo '<li><a href="' . $this->baseUrl('/admin/acomodacoes/conteudo') . '">' . $nome . '</a></li>';
                    }
                    ?>  
                </ol>
                <div class="clearfix">
                    <h1 class="pull-left">Editar <?php echo $this->title; ?></h1>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="main-box">
                    <header class="main-box-header clearfix">
                    </header>

                    <div class="main-box-body clearfix">
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        
                            <div class="form-group">
                                <label for="descricao" class="col-lg-2 control-label">Descrição</label>
                                <div class="col-lg-10">
                                	<textarea rows="" cols="" name="descricao" id="descricao" required maxlength="450" style="width: 891px; height: 169px;"><?php echo utf8_encode($this->rs["descricao"])?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button type="submit" class="btn btn-success">Salvar</button>
                                </div>
                            </div>
                            
                        </form>
                    </div>								
                </div>
            </div>	
        </div>
	</div>
</div>