<div class="row">
    <div class="col-lg-12">

        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li><a href="<?php echo $this->baseUrl('/admin'); ?>">Home</a></li>
                    <?php
                    foreach ($this->breadcrumb as $nome => $link) {
                        echo '<li><a href="' . $this->baseUrl('/admin/acomodacoes/conteudo') . '">' . $nome . '</a></li>';
                    }
                    ?>  
                </ol>
                <div class="clearfix">
                    <h1 class="pull-left">Editar <?php echo $this->title; ?></h1>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="main-box">
                    <header class="main-box-header clearfix">
                    </header>

                    <div class="main-box-body clearfix">
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        
                            	<h3><?php echo utf8_encode($this->rs["estacao_baixa"])?></h3>
                            	<div class="form-group">
                                	<label for="mes_baixa" class="col-lg-2 control-label">Mês</label>
	                                <div class="col-lg-10">
	                                    <input type="text" name="mes_baixa" class="form-control" id="mes_baixa"  maxlength="90" required value="<?php echo utf8_encode($this->rs["mes_baixa"])?>">
	                                </div>
                            	</div>
                            	<?php if($this->rs["id_quarto"] == 5){?>
                            	<div class="form-group">
                                	<label for="dbl_baixa" class="col-lg-2 control-label">PREÇO ÚNICO (ATÉ 4 PESSOAS)</label>
	                                <div class="col-lg-10">
	                                    <input type="text" name="dbl_baixa" class="form-control" id="dbl_baixa"  maxlength="90" required value="<?php echo utf8_encode($this->rs["dbl_baixa"])?>">
	                                </div>
                            	</div>
                            	
                            	<?php }else{?>
                            	<div class="form-group">
                                	<label for="dbl_baixa" class="col-lg-2 control-label">DBL</label>
	                                <div class="col-lg-10">
	                                    <input type="text" name="dbl_baixa" class="form-control" id="dbl_baixa"  maxlength="90" required value="<?php echo utf8_encode($this->rs["dbl_baixa"])?>">
	                                </div>
                            	</div>
                            	<div class="form-group">
                                	<label for="tpl_baixa" class="col-lg-2 control-label">TPL</label>
	                                <div class="col-lg-10">
	                                    <input type="text" name="tpl_baixa" class="form-control" id="tpl_baixa"  maxlength="90" required value="<?php echo utf8_encode($this->rs["tpl_baixa"])?>">
	                                </div>
                            	</div>
                            	<?php }?>
                            	<h3><?php echo utf8_encode($this->rs["estacao_alta"])?></h3>
                            	<div class="form-group">
                                	<label for="mes_alta" class="col-lg-2 control-label">Mês</label>
	                                <div class="col-lg-10">
	                                    <input type="text" name="mes_alta" class="form-control" id="mes_alta"  maxlength="90" required value="<?php echo utf8_encode($this->rs["mes_alta"])?>">
	                                </div>
                            	</div>
                            	<?php if($this->rs["id_quarto"] == 5){?>
                            	<div class="form-group">
                                	<label for="dbl_alta" class="col-lg-2 control-label">PREÇO ÚNICO (ATÉ 4 PESSOAS)</label>
	                                <div class="col-lg-10">
	                                    <input type="text" name="dbl_alta" class="form-control" id="dbl_alta"  maxlength="90" required value="<?php echo utf8_encode($this->rs["dbl_alta"])?>">
	                                </div>
                            	</div>
                            	
                            	<?php }else{?>
                            	<div class="form-group">
                                	<label for="dbl_alta" class="col-lg-2 control-label">DBL</label>
	                                <div class="col-lg-10">
	                                    <input type="text" name="dbl_alta" class="form-control" id="dbl_alta"  maxlength="90" required value="<?php echo utf8_encode($this->rs["dbl_alta"])?>">
	                                </div>
                            	</div>
                            	<div class="form-group">
                                	<label for="tpl_alta" class="col-lg-2 control-label">TPL</label>
	                                <div class="col-lg-10">
	                                    <input type="text" name="tpl_alta" class="form-control" id="tpl_alta"  maxlength="90" required value="<?php echo utf8_encode($this->rs["tpl_alta"])?>">
	                                </div>
                            	</div>
                            	<?php }?>
                            	<h3><?php echo utf8_encode($this->rs["estacao_media"])?></h3>
                            	<div class="form-group">
                                	<label for="mes_media" class="col-lg-2 control-label">Mês</label>
	                                <div class="col-lg-10">
	                                    <input type="text" name="mes_media" class="form-control" id="mes_media"  maxlength="90" required value="<?php echo utf8_encode($this->rs["mes_media"])?>">
	                                </div>
                            	</div>
                            	<?php if($this->rs["id_quarto"] == 5){?>
                            	<div class="form-group">
                                	<label for="dbl_media" class="col-lg-2 control-label">PREÇO ÚNICO (ATÉ 4 PESSOAS)</label>
	                                <div class="col-lg-10">
	                                    <input type="text" name="dbl_media" class="form-control" id="dbl_media"  maxlength="90" required value="<?php echo utf8_encode($this->rs["dbl_media"])?>">
	                                </div>
                            	</div>
                            	
                            	<?php }else{?>
                            	<div class="form-group">
                                	<label for="dbl_media" class="col-lg-2 control-label">DBL</label>
	                                <div class="col-lg-10">
	                                    <input type="text" name="dbl_media" class="form-control" id="dbl_media"  maxlength="90" required value="<?php echo utf8_encode($this->rs["dbl_media"])?>">
	                                </div>
                            	</div>
                            	<div class="form-group">
                                	<label for="tpl_media" class="col-lg-2 control-label">TPL</label>
	                                <div class="col-lg-10">
	                                    <input type="text" name="tpl_media" class="form-control" id="tpl_media"  maxlength="90" required value="<?php echo utf8_encode($this->rs["tpl_media"])?>">
	                                </div>
                            	</div>
                            	<?php }?>
                        
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button type="submit" class="btn btn-success">Salvar</button>
                                </div>
                            </div>
                            
                        </form>
                    </div>								
                </div>
            </div>	
        </div>
	</div>
</div>