<div class="row">
    <div class="col-lg-12">

        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li><a href="<?php echo $this->baseUrl('/admin'); ?>">Home</a></li>
                    <?php
                    foreach ($this->breadcrumb as $nome => $link) {
                        echo '<li><a href="' . $this->baseUrl('/admin/dolphin/conteudo') . '">' . $nome . '</a></li>';
                    }
                    ?>  
                </ol>
                <div class="clearfix">
                    <h1 class="pull-left">Editar <?php echo $this->title; ?></h1>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="main-box">
                    <header class="main-box-header clearfix">
                    </header>

                    <div class="main-box-body clearfix">
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                          
                            <div class="form-group">
                                <label for="imagem" class="col-lg-2 control-label">Selecione um tipo:</label>
                               	<div class="col-lg-5">
                               			<button type="button" id="video" class="btn btn-primary ">Video</button>
                               			<button type="button" id="image" class="btn btn-primary ">Imagem</button>
                               </div>
                            </div>
                            <div id="image1" style="display: none">
	                             <div class="form-group" >
	                                <label for="imagem" class="col-lg-2 control-label">Imagem</label>
	                                <div class="col-lg-10">
		                              <input type="file" name="imagem" class="form-control" id="imagem">
	                                    <p class="help-block">Formatos permitidos jpg, png, jpeg.</p>
	                                </div>
	                            </div>
	                            <div class="form-group" >
	                                <label for="destaque" class="col-lg-2 control-label">Destaque*</label>
	                               	<label class="radio-inline"><input type="radio" name="destaque" value='1'>Sim</label>
									<label class="radio-inline"><input type="radio" name="destaque" value='0'>Não</label>
	                            </div>
                            </div>
                            <div id="video1" style="display: none">
	                            <div class="form-group"  >
	                                <label for="video" class="col-lg-2 control-label">URL Video</label>
	                                <div class="col-lg-8">
		                              <input type="text" name="video" class="form-control" id="video" value="<?php echo $this->rs['video']?>">
	                                </div>
	                            </div>
	                            <div class="form-group" >
                                <label for="imagem_video" class="col-lg-2 control-label">Imagem do video</label>
                                <div class="col-lg-10">
	                              <input type="file" name="imagem_video" class="form-control" id="imagem_video">
                                    <p class="help-block">Formatos permitidos jpg, png, jpeg.</p>
                                </div>
                            	</div>                          
                            </div>
                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button type="submit" class="btn btn-success">Salvar</button>
                                </div>
                            </div>
                            
                        </form>
                    </div>								
                </div>
            </div>	
        </div>

    </div>
</div>
<script type="text/javascript">
$("#video").click(function(){
        $('#video1').show();
        $('#image1').hide();
});

$("#image").click(function(){
    	$('#video1').hide();
        $('#image1').show();
});   

</script>