<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="http://blackflag.rocks">

    <!-- Page title set in pageTitle controller -->
    <?php echo $this->headTitle();?>
		
    <?php  echo $this->headMeta();?>


    <?php echo $this->headLink();?>
    
   	<!-- bootstrap -->
    <link href="<?php echo $this->baseUrl('cms_novo/css/bootstrap/bootstrap.min.css'); ?>" rel="stylesheet" />

    <!-- libraries -->
    <!-- <link href="css/libs/jquery-ui-1.10.2.custom.css" rel="stylesheet" type="text/css" /> -->
    <link href="<?php echo $this->baseUrl('cms_novo/css/libs/font-awesome.css'); ?>" type="text/css" rel="stylesheet" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('cms_novo/css/libs/nanoscroller.css'); ?>" type="text/css" />

    <!-- global styles -->
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('cms_novo/css/compiled/layout.css'); ?>">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('cms_novo/css/compiled/elements.css'); ?>">

    <!-- this page specific styles -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('cms_novo/css/libs/fullcalendar.css'); ?>" type="text/css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('cms_novo/css/libs/fullcalendar.print.css'); ?>" type="text/css" media="print" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('cms_novo/css/compiled/calendar.css'); ?>" type="text/css" media="screen" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('cms_novo/css/libs/morris.css'); ?>" type="text/css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('cms_novo/css/libs/daterangepicker.css'); ?>" type="text/css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('cms_novo/css/libs/jquery-jvectormap-1.2.2.css'); ?>" type="text/css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('cms_novo/'); ?>css/libs/datepicker.css" type="text/css" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl('cms_novo/'); ?>css/libs/daterangepicker.css" type="text/css" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl('cms_novo/'); ?>css/libs/bootstrap-timepicker.css" type="text/css" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl('cms_novo/'); ?>css/libs/select2.css" type="text/css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('cms_novo/'); ?>css/libs/dropzone.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('cms_novo/'); ?>css/libs/magnific-popup.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/jquery.Jcrop.css'); ?>" type="text/css" />

    <link rel="stylesheet" href="<?php echo $this->baseUrl('/source/jquery.fancybox.css?v=2.1.5')?>" type="text/css" media="screen" />
    
    <!-- Favicon -->
    <link type="image/x-icon" href="<?php echo $this->baseUrl('cms_novo/favicon.png'); ?>" rel="shortcut icon"/>

    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('src/datepickr.min.css');?>">
    <!-- Scripts -->
    <!-- global scripts -->
    <!-- <script src="<?php echo $this->baseUrl('cms_novo/js/demo-skin-changer.js'); ?>"></script> only for demo -->

    <script src="<?php echo $this->baseUrl('cms_novo/js/jquery.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/bootstrap.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/jquery.nanoscroller.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/demo.js'); ?>"></script> <!-- only for demo -->

    <!-- this page specific scripts -->
    <script type="text/javascript" src="<?php echo $this->baseUrl('cms_novo/js/noty/packaged/jquery.noty.packaged.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/jquery-ui.custom.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/fullcalendar.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/jquery.slimscroll.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/raphael-min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/morris.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/moment.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/daterangepicker.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/jquery-jvectormap-1.2.2.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/jquery-jvectormap-world-merc-en.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/gdp-data.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/flot/jquery.flot.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/flot/jquery.flot.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/flot/jquery.flot.pie.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/flot/jquery.flot.stack.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/flot/jquery.flot.resize.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/flot/jquery.flot.time.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/js/flot/jquery.flot.threshold.js'); ?>"></script>
       
    <script src="<?php echo $this->baseUrl('cms_novo/'); ?>js/jquery.maskedinput.min.js"></script>
	<script src="<?php echo $this->baseUrl('cms_novo/'); ?>js/bootstrap-datepicker.js"></script>
	<script src="<?php echo $this->baseUrl('cms_novo/'); ?>js/daterangepicker.js"></script>
	<script src="<?php echo $this->baseUrl('cms_novo/'); ?>js/bootstrap-timepicker.min.js"></script>
	<script src="<?php echo $this->baseUrl('cms_novo/'); ?>js/select2.min.js"></script>
	<script src="<?php echo $this->baseUrl('cms_novo/'); ?>js/hogan.js"></script>
	<script src="<?php echo $this->baseUrl('cms_novo/'); ?>js/typeahead.min.js"></script>
	<script src="<?php echo $this->baseUrl('cms_novo/'); ?>js/jquery.pwstrength.js"></script>
        
    <script src="<?php echo $this->baseUrl('cms_novo/'); ?>js/jquery-ui.custom.min.js"></script>
	<script src="<?php echo $this->baseUrl('cms_novo/'); ?>js/dropzone.js"></script>
	<script src="<?php echo $this->baseUrl('cms_novo/'); ?>js/jquery.magnific-popup.min.js"></script>
    <script src="<?php echo $this->baseUrl('cms_novo/'); ?>js/jquery.price_format.2.0.min.js"></script>

    <!-- theme scripts -->
    <script src="<?php echo $this->baseUrl('cms_novo/js/scripts.js'); ?>"></script>

    <!-- google font libraries -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300|Titillium+Web:200,300,400' rel='stylesheet' type='text/css'>

    <!--[if lt IE 9]>
    	<script src="js/html5shiv.js"></script>
        <script src="js/respond.min.js"></script>
	<![endif]-->

</head>

<body class="theme-blue-gradient">
        <?php
        if(count($this->messages)){
            foreach ($this->messages as $message){
                echo "<script type=\"text/javascript\"> var n = noty({text: '$message'}); </script>";
            }
        }
        ?>
        
        <header class="navbar" id="header-navbar">
            <div class="container">
                <a href="<?php echo $this->baseUrl('/admin'); ?>" id="logo" class="navbar-brand">
                    <img src="<?php echo $this->baseUrl('cms_novo/img/logo_dolpin.png'); ?>" alt="" class="normal-logo logo-white"/>
                </a>

                <div class="clearfix">
                    <button class="navbar-toggle" data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button">
                        <span class="sr-only">Navegação em ícones</span>
                        <span class="fa fa-bars"></span>
                    </button>

                    <div class="nav-no-collapse navbar-left pull-left hidden-sm hidden-xs">
                        <ul class="nav navbar-nav pull-left">
                            <li>
                                <a class="btn" id="make-small-nav">
                                    <i class="fa fa-bars"></i>
                                </a>
                            </li>
                        </ul>
                    </div>

                    <div class="nav-no-collapse pull-right" id="header-nav">
                        <ul class="nav navbar-nav pull-right">

                            <!-- ocultando notificações
                            <li class="dropdown hidden-xs">
                                <a class="btn dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-warning"></i>
                                    <span class="count">8</span>
                                </a>
                                <ul class="dropdown-menu notifications-list">
                                    <li class="pointer">
                                        <div class="pointer-inner">
                                            <div class="arrow"></div>
                                        </div>
                                    </li>
                                    <li class="item-header">You have 6 new notifications</li>
                                    <li class="item">
                                        <a href="#">
                                            <i class="fa fa-comment"></i>
                                            <span class="content">New comment on ‘Awesome P...</span>
                                            <span class="time"><i class="fa fa-clock-o"></i>13 min.</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a href="#">
                                            <i class="fa fa-plus"></i>
                                            <span class="content">New user registration</span>
                                            <span class="time"><i class="fa fa-clock-o"></i>13 min.</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a href="#">
                                            <i class="fa fa-envelope"></i>
                                            <span class="content">New Message from George</span>
                                            <span class="time"><i class="fa fa-clock-o"></i>13 min.</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a href="#">
                                            <i class="fa fa-shopping-cart"></i>
                                            <span class="content">New purchase</span>
                                            <span class="time"><i class="fa fa-clock-o"></i>13 min.</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a href="#">
                                            <i class="fa fa-eye"></i>
                                            <span class="content">New order</span>
                                            <span class="time"><i class="fa fa-clock-o"></i>13 min.</span>
                                        </a>
                                    </li>
                                    <li class="item-footer">
                                        <a href="#">
                                            View all notifications
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            
                            <li class="dropdown hidden-xs">
                                <a class="btn dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-envelope-o"></i>
                                    <span class="count">16</span>
                                </a>
                                <ul class="dropdown-menu notifications-list messages-list">
                                    <li class="pointer">
                                        <div class="pointer-inner">
                                            <div class="arrow"></div>
                                        </div>
                                    </li>
                                    <li class="item first-item">
                                        <a href="#">
                                            <img src="<?php //echo $this->baseUrl('cms_novo/img/samples/messages-photo-1.png'); ?>" alt=""/>
                                            <span class="content">
                                                <span class="content-headline">
                                                    George Clooney
                                                </span>
                                                <span class="content-text">
                                                    Look, just because I don't be givin' no man a foot massage don't make it 
                                                    right for Marsellus to throw...
                                                </span>
                                            </span>
                                            <span class="time"><i class="fa fa-clock-o"></i>13 min.</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a href="#">
                                            <img src="<?php //echo $this->baseUrl('cms_novo/img/samples/messages-photo-2.png'); ?>" alt=""/>
                                            <span class="content">
                                                <span class="content-headline">
                                                    Emma Watson
                                                </span>
                                                <span class="content-text">
                                                    Look, just because I don't be givin' no man a foot massage don't make it 
                                                    right for Marsellus to throw...
                                                </span>
                                            </span>
                                            <span class="time"><i class="fa fa-clock-o"></i>13 min.</span>
                                        </a>
                                    </li>
                                    <li class="item">
                                        <a href="#">
                                            <img src="img/samples/messages-photo-3.png" alt=""/>
                                            <span class="content">
                                                <span class="content-headline">
                                                    Robert Downey Jr.
                                                </span>
                                                <span class="content-text">
                                                    Look, just because I don't be givin' no man a foot massage don't make it 
                                                    right for Marsellus to throw...
                                                </span>
                                            </span>
                                            <span class="time"><i class="fa fa-clock-o"></i>13 min.</span>
                                        </a>
                                    </li>
                                    <li class="item-footer">
                                        <a href="#">
                                            View all messages
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            -->
                            <!-- <li class="dropdown profile-dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <img alt="" src="<?php //echo $this->getImage($this->currentEstablishment['logo']); ?>" />
                                    <span class="hidden-xs"><?php //echo $this->currentEstablishment['name']; ?></span> <b class="caret"></b>
                                </a>
                                <?php //if(!empty($this->establishments)){ ?>
                                <ul class="dropdown-menu profiles-list">
                                    <li class="pointer">
                                        <div class="pointer-inner">
                                            <div class="arrow"></div>
                                        </div>
                                    </li>
                                    
                                    <?php   // $i = 0;
                                        //foreach($this->establishments as $establishment){
                                    ?>
                                    <li class="item <?php //if($i=0){echo 'first-item'; } ?>">
                                        <a href="<?php //echo $this->baseUrl('gestao/editar-estabelecimento/trocar-perfil/type/'.$establishment['type'].'/id/'.$establishment['id'].''); ?>">
                                            <img src="<?php //echo $this->getImage($establishment['logo']); ?>" width="40" height="40" alt=""/>
                                            <span class="content">
                                                <span class="content-headline">
                                                    <?php //echo $establishment['name']; ?>
                                                </span>
                                            </span>
                                        </a>
                                    </li>
                                    <?php //}?>
                                </ul>
                                <?php // }?>
                            </li> -->
                            <!-- <li class="hidden-xs">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-cog"></i>
                                </a>
                                <ul class="dropdown-menu options-list">
                                    <li><a href="<?php //echo $this->baseUrl('gestao/editar-dados'); ?>"><i class="fa fa-user"></i>Dados do usuário</a></li>
                                    <li><a href="<?php //echo $this->baseUrl('auth/logout'); ?>"><i class="fa fa-power-off"></i>Logout</a></li>
                                </ul>
                            </li> -->
                            <li class="hidden-xxs">
                                <a class="btn" href="<?php echo $this->baseUrl('admin/auth/logout'); ?>">
                                    <i class="fa fa-power-off"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </header>
        <div id="page-wrapper" class="container">
            <div class="row">
                <div id="nav-col">
                    <section id="col-left" class="col-left-nano">
                        <div id="col-left-inner" class="col-left-nano-content">
                            <div id="user-left-box" class="clearfix hidden-sm hidden-xs">
                                <!-- <img alt="" src="<?php //echo $this->getImage($this->currentEstablishment['logo']); ?>" /> -->
                                <div class="user-box" style="width: 180px">
                                    <span class="name">
                                        <?php echo $this->getUser();?>
                                    </span>
                                    <?php if($this->currentEstablishment['type']== 'restaurant'){ ?>
                                    <span class="status">
                                        <i class="fa fa-circle <?php echo $this->StatusEstablishment($this->currentEstablishment['is_open']); ?>"></i> <?php //echo $this->StatusEstablishment($this->currentEstablishment['is_open']); ?>
                                    </span>
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="collapse navbar-collapse navbar-ex1-collapse" id="sidebar-nav">	
                                <ul class="nav nav-pills nav-stacked">
                                
                                   <!-- <li <?php //echo $this->AtivoMenu('index'); ?>>
                                        <a href="<?php //echo $this->baseUrl('/gestao/'); ?>">
                                            <i class="fa fa-dashboard"></i>
                                            <span>Dashboard</span>
                                        </a>
                                    </li> -->
                                    
                                    <li <?php echo $this->AtivoMenu('usuarios'); ?>>
                                        <a href="<?php echo $this->baseUrl('/admin/usuarios'); ?>">
                                            <i class="fa fa-users"></i>
                                            <span>Usuários</span>
                                        </a>
                                    </li>

                                    <li <?php echo $this->AtivoMenu('dolphin'); ?>>
                                        <a href="#" class="dropdown-toggle">
                                            <i class="fa fa-inbox"></i>
                                            <span>Dolphin</span>
                                            <i class="fa fa-chevron-circle-right drop-icon"></i>
                                        </a>
                                        <ul class="submenu">
                                            <li>
                                                <a href="<?php echo $this->baseUrl('/admin/dolphin/conteudo'); ?>">
                                                    Conteúdo
                                                </a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->baseUrl('/admin/dolphin/galeria'); ?>">
                                                    Galeria
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li <?php echo $this->AtivoMenu('acomodacoes'); ?>>
                                        <a href="#" class="dropdown-toggle">
                                            <i class="fa fa-home"></i>
                                            <span>Acomodações</span>
                                            <i class="fa fa-chevron-circle-right drop-icon"></i>
                                        </a>
                                        <ul class="submenu">
                                            <li>
                                                <a href="<?php echo $this->baseUrl('/admin/acomodacoes/index/id/1'); ?>">
                                                    Standard
                                                </a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->baseUrl('/admin/acomodacoes/index/id/2'); ?>">
                                                    Compacto vista piscina
                                                </a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->baseUrl('/admin/acomodacoes/index/id/3'); ?>">
                                                    Compacto externo
                                                </a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->baseUrl('/admin/acomodacoes/index/id/4'); ?>">
                                                    Superior
                                                </a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->baseUrl('/admin/acomodacoes/index/id/5'); ?>">
                                                    Superior hidro
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    
                                    <li <?php echo $this->AtivoMenu('gastronomia'); ?>>
                                        <a href="<?php echo $this->baseUrl('/admin/gastronomia'); ?>">
                                            <i class="fa fa-apple"></i>
                                            <span>Gastronomia</span>
                                        </a>
                                    </li>
                                    <li <?php echo $this->AtivoMenu('servicos'); ?>>
                                        <a href="<?php echo $this->baseUrl('/admin/servicos'); ?>">
                                            <i class="fa fa-lock"></i>
                                            <span>Serviços e Passeios</span>
                                        </a>
                                    </li>
                               		<li <?php echo $this->AtivoMenu('pacotes'); ?>>
                                       <a href="#" class="dropdown-toggle"> 
                                            <i class="fa fa-usd"></i> 
                                             <span>Pacotes</span> 
                                            <i class="fa fa-chevron-circle-right drop-icon"></i> 
                                         </a>
                                         <ul class="submenu"> 
                                            <li> 
                                                <a href="<?php echo $this->baseUrl('/admin/pacotes/index/'); ?>">
                                                    Lista de Pacotes
                                                 </a>
                                             </li> 
                                         
                                             <li> 
                                               <a href="<?php echo $this->baseUrl('/admin/pacotes/editar-conteudo/id/1'); ?>"> 
                                                    Conteúdo 
                                                 </a> 
                                             </li> 
                                          </ul>
                                    </li> 
                                    
                                    
                                    
                                    
                                    
                                    <li <?php //echo $this->AtivoMenu('tarifas'); ?>>
<!--                                         <a href="#" class="dropdown-toggle"> -->
<!--                                             <i class="fa fa-usd"></i> -->
<!--                                             <span>Tarifas</span> -->
<!--                                             <i class="fa fa-chevron-circle-right drop-icon"></i> -->
<!--                                         </a> -->
<!--                                         <ul class="submenu"> -->
<!--                                             <li> -->
<!--                                                <a href="<?php //echo $this->baseUrl('/admin/tarifas/index/'); ?>">-->
<!--                                                     Pacotes -->
<!--                                                 </a> -->
<!--                                             </li> -->
<!--                                             <li> -->
<!--                                                <a href="<?php //echo $this->baseUrl('/admin/tarifas/editar-opcionais/id/1'); ?>"> -->
<!--                                                     Opcionais -->
<!--                                                 </a> -->
<!--                                             </li> -->
<!--                                             <li> -->
<!--                                                <a href="<?php //echo $this->baseUrl('/admin/tarifas/editar-conteudo/id/1'); ?>"> -->
<!--                                                     Conteúdo -->
<!--                                                 </a> -->
<!--                                             </li> -->
<!--                                         </ul> -->
<!--                                     </li> -->

                                </ul>
                            </div>
                        </div>
                    </section>
                </div>
                <div id="content-wrapper">
                    <?php echo $this->layout()->content; ?>
                    <footer id="footer-bar" class="row">
                        <p id="footer-copyright" class="col-xs-12">
                            &copy; <?php echo date('Y');?> <a href="http://inndeia.com/" target="_blank">Inndeia</a>. Powered by Inndeia.
                        </p>
                    </footer>
                </div>
            </div>
        </div>

    </body>
</html>
