<?php if ($this->pageCount): ?>

<ul class="pagination pull-right">
    <?php if (isset($this->previous) ): ?>
        <li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>"><i class="fa fa-chevron-left disabled"></i></a></li>
    <?php endif; ?>
        
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
        <?php else: ?>
            <li><a href="#"><?php echo $page; ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php if (isset($this->next)): ?>
        <li><a href="<?php echo $this->url(array('page' => $this->next)); ?>"><i class="fa fa-chevron-right"></i></a></li>
    <?php endif; ?>
</ul>
<?php endif; ?>